// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideLogo: typeof import('./layouts/components/AsideLogo.vue')['default']
    AsideMenu: typeof import('./layouts/components/AsideMenu.vue')['default']
    AsideMenuItem: typeof import('./layouts/components/AsideMenuItem.vue')['default']
    AsideMenuItemTitle: typeof import('./layouts/components/AsideMenuItemTitle.vue')['default']
    ElAside: typeof import('element-plus/lib')['ElAside']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/lib')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/lib')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDrawer: typeof import('element-plus/lib')['ElDrawer']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/lib')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconAntDesignGithubOutlined: typeof import('~icons/ant-design/github-outlined')['default']
    IconAntDesignLockOutlined: typeof import('~icons/ant-design/lock-outlined')['default']
    IconAntDesignMenuUnfoldOutlined: typeof import('~icons/ant-design/menu-unfold-outlined')['default']
    IconAntDesignReloadOutlined: typeof import('~icons/ant-design/reload-outlined')['default']
    IconAntDesignSearchOutlined: typeof import('~icons/ant-design/search-outlined')['default']
    IconAntDesignSettingOutlined: typeof import('~icons/ant-design/setting-outlined')['default']
    IconAntDesignUserOutlined: typeof import('~icons/ant-design/user-outlined')['default']
    Navbar: typeof import('./layouts/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsView: typeof import('./layouts/components/TabsView.vue')['default']
  }
}
