// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/lib')['ElAside']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElMain: typeof import('element-plus/lib')['ElMain']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IAntDesignUserOutlined: typeof import('~icons/ant-design/user-outlined')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
